services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
  mlflow-server:
    # image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "8080:8080"
    volumes:
      - ./mlflow-data:/mlflow
    command: mlflow server --allowed-hosts "mlflow-server:*,0.0.0.0:*,89.167.19.169:*" --host 0.0.0.0 --port 8080
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "python",
    #       "-c",
    #       "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')",
    #     ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 30
  event_collector:
    build: 
      context: .
      dockerfile: event_collector/Dockerfile
    container_name: event_collector_dc
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: uvicorn event_collector.main:app --port 5000 --host 0.0.0.0
    healthcheck:
      test: curl -X 'GET' 'localhost:5000/healthcheck'
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 2m
  recommendations:
    build: 
      context: .
      dockerfile: recommendations/Dockerfile
    container_name: recommendations_dc
    environment:
      - LOGURU_COLORIZE=YES
    ports:
      - "5001:5001"
    depends_on:
      - redis
    volumes:
      - ./recommendations:/recommendations
      - ./data:/data
      - ./logs:/logs
    command: uvicorn recommendations.main:app --port 5001 --host 0.0.0.0
    healthcheck:
      test: curl -X 'GET' 'localhost:5001/healthcheck'
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 2m
  webapp:
    build: 
      context: .
      dockerfile: webapp/Dockerfile
    depends_on:
      event_collector:
        condition: service_healthy
      recommendations:
        condition: service_healthy
    container_name: webapp_dc
    ports:
      - "8000:8000"
    command: python app.py
  regular_pipeline:
    build: 
      context: .
      dockerfile: regular_pipeline/Dockerfile
    container_name: regular_pipeline_dc
    environment:
      - LOGURU_COLORIZE=YES
    depends_on:
      rabbitmq:
        condition: service_healthy
      webapp:
        condition: service_started
    volumes:
      - ./regular_pipeline:/regular_pipeline
      - ./data:/data
      - ./logs:/logs
    command: python -m regular_pipeline.main
